## Тема “Создание признакового пространства”

### Подготовка:

In [2]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec

import warnings 
warnings.filterwarnings("ignore")
import os

In [3]:
df = pd.read_pickle('tweet_data.pkl')
df.head(2)

,id,label,tweet,clean_tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0.0,@user when a father is dysfunctional and is s...,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ...","[father, dysfunct, selfish, drag, kid, dysfunc...","[father, dysfunctional, selfish, drag, kid, dy..."
1,2,0.0,@user @user thanks for #lyft credit i can't us...,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee...","[thank, lyft, credit, use, caus, offer, wheelc...","[thanks, lyft, credit, use, cause, offer, whee..."

In [4]:
def fit_model(df, type_model, column_value, max_df=0.9, max_features=1000, stop_words='english'):
    model = type_model(max_df=max_df, stop_words=stop_words, max_features=max_features)
    values = df[column_value].astype('str')
    BOW = model.fit_transform(values)
    feature_names = model.get_feature_names()
    return pd.DataFrame(BOW.toarray(), columns = feature_names)

1. Создайте мешок слов с помощью sklearn.feature_extraction.text.CountVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
 -	Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
 -	Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
 -	Исключим стоп-слова с помощью stop_words='english'.
 -	Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью CountVectorizer.get_feature_names().

In [5]:
tweet_stemmed_df = fit_model(df, CountVectorizer, 'tweet_stemmed', max_df=0.9, max_features=1000, stop_words='english')
tweet_stemmed_df.head()

,abl,absolut,accept,account,act,action,activ,actor,actual,ad,...,yeah,year,yesterday,yo,yoga,york,young,youtub,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
tweet_lemmatized_df = fit_model(df, CountVectorizer, 'tweet_lemmatized', max_df=0.9, max_features=1000, stop_words='english')
tweet_lemmatized_df.head()

,able,absolutely,account,act,action,actor,actually,adapt,add,adventure,...,yes,yesterday,yo,yoga,york,young,youth,youtube,yr,yummy
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

2. Создайте мешок слов с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
 -	Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
 -	Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
 -	Исключим стоп-слова с помощью stop_words='english'.
 -	Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью TfidfVectorizer.get_feature_names().

In [7]:
tweet_stemmed_df = fit_model(df, TfidfVectorizer, 'tweet_stemmed', max_df=0.9, max_features=1000, stop_words='english')
tweet_stemmed_df.head()

,abl,absolut,accept,account,act,action,activ,actor,actual,ad,...,yeah,year,yesterday,yo,yoga,york,young,youtub,yr,yummi
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
tweet_lemmatized_df = fit_model(df, TfidfVectorizer, 'tweet_lemmatized', max_df=0.9, max_features=1000, stop_words='english')
tweet_lemmatized_df.head()

,able,absolutely,account,act,action,actor,actually,adapt,add,adventure,...,yes,yesterday,yo,yoga,york,young,youth,youtube,yr,yummy
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

3. Натренируем gensim.models.Word2Vec модель на наших данных.
 -	Тренировать будем на токенизированных твитах combine_df['tweet_token']
 -	Установим следующие параметры: size=200, window=5, min_count=2, sg = 1, hs = 0, negative = 10, workers= 32, seed = 34.
 -	Используем функцию train() с параметром total_examples равным длине combine_df['tweet_token'], количество epochs установим 20.

In [9]:
model = Word2Vec(sentences=df['tweet_token'],
                    size=200,
                    window=5,
                    min_count=2, 
                    sg=1,
                    hs=0,
                    negative=10,
                    workers=32,
                    seed=34)

In [10]:
model.train(df['tweet_token'], total_examples=len(df['tweet_token']), epochs=20)

(9140382, 11726520)

4. Давайте немного потестируем нашу модель Word2Vec и посмотрим, как она работает. Мы зададим слово positive = "dinner", и модель вытащит из корпуса наиболее похожие слова c помощью функции most_similar. То же самое попробуем со словом "trump".

In [11]:
model.most_similar(positive = "dinner")

[('cookout', 0.549928605556488),
 ('bihdaydinner', 0.5471246242523193),
 ('bolognese', 0.537915825843811),
 ('shawarma', 0.5360479354858398),
 ('whoopppp', 0.533271074295044),
 ('sissy', 0.5205006003379822),
 ('tacotuesday', 0.5167436003684998),
 ('lastnight', 0.5132229328155518),
 ('hamburger', 0.5130410194396973),
 ('waterloo', 0.5104011297225952)]

In [12]:
model.most_similar(positive = "trump")

[('donald', 0.5618138909339905),
 ('unfit', 0.522334098815918),
 ('dumptrump', 0.5153286457061768),
 ('donaldtrump', 0.5152258276939392),
 ('unfavorability', 0.5134192705154419),
 ('fuhered', 0.5103771686553955),
 ('chopra', 0.5102115869522095),
 ('crony', 0.5100200772285461),
 ('conman', 0.5048657059669495),
 ('carl', 0.5013986825942993)]

5. Из приведенных выше примеров мы видим, что наша модель word2vec хорошо справляется с поиском наиболее похожих слов для данного слова. Но как она это делает? Она изучила векторы для каждого уникального слова наших данных и использует косинусное сходство, чтобы найти наиболее похожие векторы (слова).
Давайте проверим векторное представление любого слова из нашего корпуса, например "food".

In [13]:
model.wv['food']

array([ 0.6637808 ,  0.20503165, -0.12931526,  0.30524525,  0.07817683,
       -0.8936081 ,  0.14668563,  1.201811  ,  0.21320687,  0.76001483,
        0.40682337, -0.6730745 , -0.22134544,  0.58630264, -1.1694694 ,
       -0.6312182 ,  0.03102705,  0.10746347,  0.31303653, -0.22719851,
        0.7652215 ,  0.03983815, -0.51403725, -0.21060602,  0.40639105,
       -0.24675915, -0.7090412 , -0.40103963, -0.25174257,  0.09121281,
        0.00364224, -0.22739764,  0.30795074,  0.1642498 , -0.8903084 ,
        0.39822772, -0.14041023, -0.07735955,  0.16278557, -0.00965097,
        0.2748203 ,  0.7685171 , -0.18867262,  0.02977176,  0.38200435,
        0.60235506, -0.14408185, -0.27826595,  0.23700005, -0.8706169 ,
       -0.49088126,  0.4048085 ,  0.25440136,  0.33420604,  0.18232477,
        0.05767141, -0.01220713, -0.43365958,  0.10889502,  0.14042863,
        0.45815283, -0.5499214 ,  0.3922143 , -0.08906611,  0.1731375 ,
        0.03084033, -0.01855678, -0.5742612 ,  0.66712266,  0.5216797 ,
        0.01173525,  0.8107163 ,  0.03513043,  0.7058565 , -0.4990908 ,
        0.29303336, -0.21995464, -0.14100689, -0.3148691 ,  0.09091136,
        0.22393517, -0.23748527, -0.5159895 , -0.87599856, -0.24814318,
        0.27727926, -0.24663322,  0.02978991, -0.15612487, -0.17909631,
        0.21486598,  0.05431157, -0.616604  ,  0.6663921 , -0.21684311,
        0.280546  ,  0.3926192 ,  0.5191566 , -0.10156374, -0.26799488,
        0.5449002 ,  0.05593084,  0.6333419 , -0.12273514,  0.17777498,
       -0.12979381,  0.35337406, -0.14588831, -0.12336434, -0.32997617,
       -0.73354423,  0.22265181, -0.42437038,  0.0651901 ,  0.06380519,
        0.41372338, -0.11524019,  1.3759005 ,  0.02008033,  0.0034139 ,
        0.12483598,  0.16081232,  0.9031977 ,  0.30009514, -0.23283947,
       -0.11134318, -0.55273795,  0.5633111 ,  0.4481876 , -0.05743062,
       -0.6946581 , -0.45476216,  0.49802563,  0.05336739,  0.13492103,
       -0.42190996, -0.4410298 ,  0.25561917, -0.20887467,  1.0745653 ,
       -0.17475903,  0.1785945 ,  0.28281933, -0.01260448, -0.08754025,
        0.2280471 , -0.01177431,  0.5323528 , -0.5431266 ,  0.14266522,
        0.23827416, -0.01629792, -0.10138186, -0.15580897, -0.7101418 ,
       -0.7422624 ,  0.3650644 ,  0.32327178,  0.41760755, -0.29202473,
       -0.8021154 , -0.08020862, -0.0955185 , -0.55588365, -0.65710723,
       -0.6243278 ,  1.1296401 , -0.06364523, -0.15879178, -0.31005728,
       -0.36670926, -0.168639  , -0.9857022 , -0.6422717 ,  0.38171014,
        0.05199871, -0.12724985,  0.0042444 , -0.32321122, -0.26064196,
       -0.0108977 , -0.11438288,  0.19549266,  0.69195205,  0.60082513,
        0.07806801, -0.0231398 ,  0.51356006,  0.09816629, -0.2875278 ,
       -0.59677345, -0.1429624 , -0.06632759,  0.32371613, -0.01336089,
        0.6821833 ,  0.26826796,  0.3051843 , -0.1415956 ,  0.38355637],
      dtype=float32)

6. Поскольку наши данные содержат твиты, а не только слова, нам придется придумать способ использовать векторы слов из модели word2vec для создания векторного представления всего твита. Существует простое решение этой проблемы, мы можем просто взять среднее значение всех векторов слов, присутствующих в твите. Длина результирующего вектора будет одинаковой, то есть 200. Мы повторим тот же процесс для всех твитов в наших данных и получим их векторы. Теперь у нас есть 200 функций word2vec для наших данных.

In [15]:
vec_size = 200

wordvec_df = np.zeros((len(df) , vec_size))
for i, tweet in enumerate(df['tweet_token']):
    vec = np.zeros((1, vec_size))
    for word in tweet:
        try:
            vec += model.wv[word].reshape((1,vec_size))
        except:
            continue            
    vec /= len(tweet)
    wordvec_df[i] = vec

In [16]:
wordvec_df.shape

(49159, 200)